### ISSUE TITLE
チャットでやることリスト

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#86]
### Todo
- [x]  3種類のチャットルームを作成できるようにする(公開、非公開、パスワードで保護)  
  - https://github.com/ryo-manba/ft_transcendence/pull/90
  - https://github.com/ryo-manba/ft_transcendence/pull/112
  - https://github.com/ryo-manba/ft_transcendence/pull/151
- [x]  DM機能
  - https://github.com/ryo-manba/ft_transcendence/pull/209
- [x] チャンネルを作成したユーザーは、そのチャンネルから離れるまでchannel ownerにする
  - https://github.com/ryo-manba/ft_transcendence/pull/234
- [x] チャットページから、他のユーザーをゲームに招待できるようにする
  - https://github.com/ryo-manba/ft_transcendence/pull/163
- [x] チャットページから、他のユーザーのプロフィールにアクセスできるようにする
  - https://github.com/ryo-manba/ft_transcendence/pull/159
- [x] ユーザーをブロックできるようにする
  - https://github.com/ryo-manba/ft_transcendence/pull/251

### その他のルール
**チャンネルの管理者の権限**
- ユーザーを一定期間禁止(BAN)したり、ミュートできる
- [x] ミュート機能
  - https://github.com/ryo-manba/ft_transcendence/pull/193
  -> https://github.com/ryo-manba/ft_transcendence/pull/199
- [x] BAN機能
  - https://github.com/ryo-manba/ft_transcendence/pull/186

**チャンネルオーナーの権限**
- チャンネル管理者でもある
- [x] チャンネルにアクセスするための**パスワード設定、変更、削除**を設定できる
  - https://github.com/ryo-manba/ft_transcendence/pull/174
- [x] 他のユーザーを管理者に設定できる(複数人)
  - https://github.com/ryo-manba/ft_transcendence/pull/162

**Comment by ryo-manba** [comment]
機能はすべて作成できたのでCloseする。
